add css classes
networkteam/Networkteam.Neos.ShopwareIntegration pull request #3
Opened 2020-08-20 05:53 UTC by esdete2

* add css classes to components
* fix some small bugs

2020-08-20 13:42 UTC, suffle requested changes

2020-08-20 13:42 UTC, suffle commented on Resources/Private/Javascript/Components/CartItems.js
>          !loading ?
This is a bit hard to read, why do we need another checked, if it is loaded here? As long as there is a loading overlay on top, the user knows whats happening

2020-08-20 13:42 UTC, suffle commented on Resources/Private/Javascript/Components/CartSummary.js
> +          <dt className='c-cart-summary__label c-cart-summary__label--count'>Different products:</dt>
can we put a little more structure in there, like warp the term and description in a container, so that i can style them as a block?

2020-08-20 13:42 UTC, suffle commented on Resources/Private/Javascript/Components/CartSummary.js
> +          <dt className='c-cart-summary__label c-cart-summary__label--count'>Different products:</dt>
Also we need to find a solution for the labels so that they are at least translatable

2020-08-20 13:42 UTC, suffle commented on Resources/Private/Javascript/Components/Orders.js
> +              <dl className='c-orders__order-details'>
There is a lot of similar markup to e.g. the cart summary, can we find a component, which is easily usable? Like `<DefinitionList><DefinitionList.DefinitionItem label={Order} value={order.orderNumber} /><DefinitionList>`

2020-08-20 13:42 UTC, suffle commented on Resources/Private/Javascript/Components/Orders.js
> +          <div className='c-orders__empty-message'>{emptyMessage}</div>
see above: do we need the loading state check here?

2020-08-21 12:01 UTC, esdete2 commented on Resources/Private/Javascript/Components/CartItems.js
>          !loading ?
Otherwise the message is displayed before the actual content is loaded. The overlay may be transparent.

2020-08-21 12:01 UTC, esdete2 commented on Resources/Private/Javascript/Components/Orders.js
> +          <div className='c-orders__empty-message'>{emptyMessage}</div>
See my answer above.

2020-08-21 20:31 UTC, esdete2 commented on Resources/Private/Javascript/Components/Orders.js
> +              <dl className='c-orders__order-details'>
DefinitionList component added

2020-08-21 22:25 UTC, esdete2 commented on Resources/Private/Javascript/Components/CartSummary.js
> +          <dt className='c-cart-summary__label c-cart-summary__label--count'>Different products:</dt>
Wrapped in div. Translatability added in #6

2020-08-24 14:35 UTC, suffle commented on Resources/Private/Javascript/Components/DefinitionList.js
> +import { classList } from '../Helper/utilities';
i just saw this, wouldnt it be better to use an npm package here? Like react-bem-helper or classnames?

2020-08-24 14:35 UTC, suffle commented on Resources/Private/Javascript/Components/DefinitionList.js
> +      ['c-definition-list__item--' + modifier]: modifier
To be honest, I'm not sure if this is a good way to use BEM (and what i mean is: i really dont know). In my eyes a modifier should be set to change appearance, state or behavior on a comprehensible way (like color or size) and should not be used to give things names. Maybe thats what mixes should be used for? Or maybe BEM is not the right way to go here?

2020-08-24 14:35 UTC, suffle commented on Resources/Private/Javascript/Components/DefinitionList.js
> +export const DefinitionItem = ({ label, value, modifier }) => {
A definition item can't or shouldn't be used without the list,. so i would make it a subitem. Before exporting the DefinitionList do something like DeifinitionList.DeifinitionItem = DefinitionItem. You don't need to import it then and can just use it as DefinitionList.DefinitionItem

2020-08-24 14:35 UTC, suffle commented on Resources/Private/Javascript/Components/CartItems.js
>          !loading ?
I prefer showing some initial state (like this message) instead of just a loading-spinner, but that's up to you

2020-08-26 13:38 UTC, suffle commented on Resources/Private/Javascript/Components/DefinitionList.js
> +import { classList } from '../Helper/utilities';
will be moved to improvements

2020-08-26 13:43 UTC, suffle commented on Resources/Private/Javascript/Components/DefinitionList.js
> +export const DefinitionItem = ({ label, value, modifier }) => {
Will be fixed in later improvements

2020-08-26 13:43 UTC, suffle commented on Resources/Private/Javascript/Components/DefinitionList.js
> +      ['c-definition-list__item--' + modifier]: modifier
Will be discussed and maybe fixed in later improvements

2020-08-26 13:46 UTC, suffle approved these changes

2020-08-26 13:46 UTC, merged